=== victor-risco-ruiz/Llenguatges-de-Marques-i-SGE/RA4 XML & JSON/exercicis_validacio_xsd/exercici1/exercici1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="biblioteca">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="llibre" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titol" type="xs:string" />
                            <xs:element name="autor" type="xs:string" />
                            <xs:element name="any" type="xs:positiveInteger" />
                            <xs:element name="preu" type="xs:decimal" />
                        </xs:sequence>
                        <xs:attribute name="isbn" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
  </xs:element>

</xs:schema>

=== victor-risco-ruiz/Llenguatges-de-Marques-i-SGE/RA4 XML & JSON/exercicis_validacio_xsd/exercici1/exercici1.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./exercici1.xsd">
    <llibre isbn="1">
        <titol>El pequenyo pepe</titol>
        <autor>Pepito de los palotes</autor>
        <any>2020</any>
        <preu>13.99</preu>
    </llibre>
    <llibre isbn="2">
        <titol>Los power rangers</titol>
        <autor>Ricardo</autor>
        <any>2000</any>
        <preu>15.99</preu>
    </llibre>
    <llibre isbn="3">
        <titol>Harry Potter</titol>
        <autor>J.K Rowling</autor>
        <any>1999</any>
        <preu>20.99</preu>
    </llibre>
</biblioteca>
